### ISSUE TITLE
Getting error: failed to fetch pull request info after latest update. 

### ISSUE THREAD

**Issue by santhoshar-bt** [wareismymind/peer#158]
Getting this error on 
peer show
![image](https://user-images.githubusercontent.com/83311392/162815424-3f44cc03-f61c-4f02-bf9e-7f07630d7444.png)

Has there been any config changes that needs to be made for peer to work?

**Comment by Insomniak47** [comment]
Hey dude! Sorry for the delay. I'm not having any issues. Could you toss me an anonymized version of your config so I can take a peek? @tshowers-bt you have any idea what might have busted this?

**Comment by Insomniak47** [comment]
So @tshowers-bt is using the following command `peer -w -f '!title:((chore|build)\((deps|master\)))'` and having an issue but not having it without the filter. I've tried the same filter locally and I'm getting no problems which makes me think that it might be a PR that both of you have that peer doesn't handle nicely either in parsing or processing. @santhoshar-bt if you've got a few at some point mind just spinning up peer from the repo and running it in the debugger I'd love to see where it was introduced given the config and pipelining changes introduced in 1.8

**Comment by santhoshar-bt** [comment]
restarting the system makes me sound like stupid!! ( if something goes wrong, restart the system lol)  @tshowers-bt me and Leo had issues at the same time. So I believe it is one of the PR that is throwing this off.

**Comment by Insomniak47** [comment]
@tshowers-bt  is getting it now too so I'm wondering if I busted something in the async enumerable changes. Let me know if it comes up often/at all and I'll take another pass through the async enumerable stuff tn

**Comment by Insomniak47** [comment]
I think this was solved in : #160  but if it comes up again just re-open this :)
