### ISSUE TITLE
Identify required OAuth scopes

### ISSUE THREAD

**Issue by tshowers-bt** [wareismymind/peer#161]
Determine and document the minimum set of required OAuth scopes for the PAT.

**Comment by Insomniak47** [comment]
I checked this out. If we only want public repos it's just repo:status but if we want to have private ones in there we need all of the repo scope (AFAICT, the docs aren't great)

**Comment by Insomniak47** [comment]
@tshowers-bt -- Checked this with a few tokens. This is true - Closing
