### ISSUE TITLE
Create interfaces for conditionally registering PullRequestFetchers

### ISSUE THREAD

**Issue by Insomniak47** [wareismymind/peer#4]
Since we want to be able to support multiple fetchers and not load them in when we don't have to we should only register the types required for different providers when they are configured.

Given: 
- A Provider definition in ~/.peer/config.json with a specific provider name
Then:
- Register the required classes for the provider and the provider itself as the IPullRequestProvider interface (or similarly named interface).

2021-10-10
#7 is being started before this issue but it refers to setting up the PR fetcher conditionally using the interfaces described in this issue. Instead when this issue is worked on the  program should be updated to register fetcher introduced by #7 conditionally using the interfaces this issue introduces.

**Comment by tshowers-bt** [comment]
We should maybe talk about the big picture of behaviour/configurability so we can come up with a format for how the config file will specify what to watch and what to use to watch it. We can probably default to things whose origin is '*github.com*' using the github provider too.

**Comment by Insomniak47** [comment]
Closed by #26
